### ISSUE TITLE
Linear Interpolation incorrect 

### ISSUE THREAD

**Issue by TBLeftHand** [PyPlr/cvd_pupillometry#5] opened 2022-11-24 09:00 UTC
Hello, 

im trying to preprocess my pupillary light reflex data. While doing that the linear interpolation makes strange dips that make my data useless. This is the code im using and the plot it creates: 

![Code](https://user-images.githubusercontent.com/118968438/203738944-447faa24-c50f-44d2-9d5b-55aeca979276.PNG)
![Plot](https://user-images.githubusercontent.com/118968438/203739029-d3db3006-41f3-462d-b510-2426dc98c2d0.png)

**Comment by jtmbeta** [comment] 2022-11-24 12:15
Hello,

Are you referring to the two dips on the final PLR? You could try setting a higher threshold for confidence (e.g. 0.95) and the first derivative (e.g. 3.5). 

If you continue to experience issues, please upload a minimal example including the script and data.

Joel

**Comment by TBLeftHand** [comment] 2022-12-21 08:34
Hi Joel, 

thank you for your comment. While changing the confidence and first derivate I could get rid of the artefacts. 
Now I have another question and actually tried to write you an email but the mail server says that the email doesn't exist. 

We are trying to get reproducible results in the PLR with the Pupil Core. While we tried to make our experiment settings as similar as possible for every trial, we don't get these results. 

I have read your publication and  saw that you experienced similar problems on subject 3. Do you have any suggestions how to make the results more reliable? 

With best regards

Till

**Comment by jtmbeta** [comment] 2022-12-21 12:52
Hi Till

I'm glad to hear you were able to remove the artefacts. 

Reproducibility of PLR measures with a Pupil Core system can be problematic between/within sessions, because the 3D eye model (from which pupil measurements are derived) is dependant on geometry. If the eye cameras are not positioned exactly the same between sessions, the model fit (and therefore the pupil size measurements) will be slightly different. Within a session, the 3D model continually updates to account for potential headset slippage. If headset slippage is not going to a be a problem (i.e., your subject is using a chinrest, or not moving about very much), it may help to use the 'Freeze Model' feature in pupil capture once the model has a good fit. 

Also, if you don't care about absolute pupil size in mm, converting the pupil measurements to percent signal change from a baseline may help. 

I will now close this issue. If you continue to run into issues relating to Pupil Core, I suggest searching the Pupil LAbs chat archive and posing your questions there.

https://chat-archive.pupil-labs.com/

Joel

**Closed by jtmbeta** 2022-12-21 12:52 UTC

**Comment by TBLeftHand** [comment] 2022-12-21 15:10
Thank you!
